## **Домашняя работа "Функции потерь и оптимизация"**

- Реализовать самостоятельно логистическую регрессию  
- Обучить ее методом градиентного спуска:  
Методом nesterov momentum  
Методом rmsprop
- В качестве dataset’а взять Iris, оставив 2 класса:  
Iris Versicolor  
Iris Virginica

In [37]:
from sklearn import datasets
from matplotlib import pyplot as plt
%matplotlib inline
import numpy as np

In [60]:
iris = datasets.load_iris()

In [61]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


### "Убираем" лишнее и меняем классификации на 0 и 1

In [127]:
X = []
Y = []
for idx, item in enumerate(iris.target):
    if item != 0:
        X.append(iris.data[idx])
        Y.append(item-1)

X = np.asarray(X)
Y = np.asarray(Y)

#print(Y)

In [128]:
X.shape

(100, 4)

### Классифицирующая функция, пропущенная через сигмоиду

In [130]:
def predict(theta, X):
    predict = theta[0] + theta[1] * X[:, 0] + theta[2] * X[:, 1] + theta[3] * X[:, 2] + theta[4] * X[:, 3]
    sigm = 1. / (1 + np.exp(-predict))
    return sigm

### Градиентный спуск

In [140]:
lr = 0.05
theta = []
theta = np.random.normal(size=(5,))
grad_loss_hist = []
for _ in range(1000):
    sigm = predict(theta, X)
    theta[0] -= lr * np.sum(sigm - Y)/len(sigm)
    theta[1] -= lr * np.sum((sigm - Y) * X[:, 0])/len(sigm)
    theta[2] -= lr * np.sum((sigm - Y) * X[:, 1])/len(sigm)
    theta[3] -= lr * np.sum((sigm - Y) * X[:, 2])/len(sigm)
    theta[4] -= lr * np.sum((sigm - Y) * X[:, 3])/len(sigm)
    loss = - np.mean(np.log(sigm) * Y + np.log(1 - sigm) * (1 - Y))
    print(theta)
    grad_loss_hist.append(loss)

[-0.09356893  0.33213355 -0.71801959  0.64685223 -0.61360899]
[-0.11254923  0.22031172 -0.77001882  0.56848976 -0.63702232]
[-0.12149629  0.17094435 -0.7928807   0.53888967 -0.64348729]
[-0.12432447  0.16007176 -0.79796356  0.53951037 -0.63951144]
[-0.12624222  0.1549335  -0.80040929  0.54461922 -0.63399752]
[-0.12807693  0.15030627 -0.80261962  0.55010538 -0.62836173]
[-0.12990101  0.14573275 -0.8048047   0.55560894 -0.62272798]
[-0.13172051  0.14117489 -0.80698201  0.56110003 -0.61710654]
[-0.13353594  0.13662952 -0.80915305  0.56657619 -0.61149823]
[-0.13534734  0.13209633 -0.81131795  0.57203728 -0.6059031 ]
[-0.13715473  0.12757526 -0.81347675  0.57748331 -0.60032111]
[-0.13895813  0.1230663  -0.81562948  0.58291435 -0.59475224]
[-0.14075755  0.1185694  -0.81777617  0.58833042 -0.58919645]
[-0.14255299  0.11408452 -0.81991684  0.59373158 -0.58365371]
[-0.14434449  0.10961164 -0.82205153  0.59911788 -0.57812399]
[-0.14613203  0.10515073 -0.82418025  0.60448936 -0.57260725]
[-0.1479

In [141]:
grad_loss_hist

[1.695584535816165,
 1.0450599897240096,
 0.7131092033721381,
 0.6664480905618501,
 0.6637766408831357,
 0.6619329585170752,
 0.6601048953074584,
 0.6582862998116924,
 0.6564770790435078,
 0.6546771820670658,
 0.6528865583856035,
 0.6511051576520136,
 0.6493329296688062,
 0.647569824390414,
 0.6458157919254901,
 0.6440707825391497,
 0.642334746655155,
 0.6406076348580438,
 0.6388893978952024,
 0.6371799866788799,
 0.6354793522881509,
 0.6337874459708207,
 0.6321042191452778,
 0.6304296234022928,
 0.6287636105067631,
 0.6271061323994066,
 0.6254571411984025,
 0.6238165892009817,
 0.6221844288849656,
 0.6205606129102553,
 0.6189450941202712,
 0.6173378255433437,
 0.6157387603940554,
 0.6141478520745359,
 0.6125650541757092,
 0.6109903204784948,
 0.6094236049549623,
 0.607864861769442,
 0.6063140452795893,
 0.6047711100374062,
 0.6032360107902185,
 0.6017087024816106,
 0.6001891402523186,
 0.5986772794410801,
 0.5971730755854449,
 0.5956764844225443,
 0.5941874618898201,
 0.59270596412571

### Проверяем количество ошибок

In [152]:
error = 0
for idx, item in enumerate(np.around(predict(theta, X))):
    if item != Y[idx]:
        error += 1
error

2

### Сравниваем результаты

In [144]:
np.matrix([np.around(predict(theta, X)), Y]).T

matrix([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1

### Метод nesterov momentum

In [145]:
lr = 0.05
theta = []
theta = np.random.normal(size=(5,))
vel_pred = np.zeros(5)
vel = np.zeros(5)
nest_loss_hist = []
gamma = 0.975
for _ in range(1000):
    sigm = predict(theta, X)
    loss = - np.mean(np.log(sigm) * Y + np.log(1 - sigm) * (1 - Y))
    nest_loss_hist.append(loss)
    
    sigm = predict(theta - gamma * vel_pred, X)
    
    vel[0] = (gamma * vel_pred[0] + lr * np.sum(sigm - Y))/len(sigm)
    vel[1] = (gamma * vel_pred[1] + lr * np.sum((sigm - Y) * X[:, 0]))/len(sigm)
    vel[2] = (gamma * vel_pred[2] + lr * np.sum((sigm - Y) * X[:, 1]))/len(sigm)
    vel[3] = (gamma * vel_pred[3] + lr * np.sum((sigm - Y) * X[:, 2]))/len(sigm)
    vel[4] = (gamma * vel_pred[4] + lr * np.sum((sigm - Y) * X[:, 3]))/len(sigm)
    theta -= vel
    print(theta)

    vel_pred = vel

[-0.87680082 -1.40752534 -1.42695567  1.9021618   1.57045511]
[-0.87642734 -1.40141925 -1.4244713   1.9100275   1.5745315 ]
[-0.86312669 -1.3123598  -1.3841443   1.98514046  1.60219371]
[-0.86651136 -1.32991133 -1.39254847  1.97445879  1.59994984]
[-0.85815152 -1.2727934  -1.36672422  2.02328919  1.61828328]
[-0.8626246  -1.29715658 -1.3782707   2.00732082  1.61425405]
[-0.8572191  -1.25903022 -1.36110792  2.04072087  1.62716372]
[-0.86154594 -1.28249187 -1.37223673  2.0254317   1.62335722]
[-0.85801347 -1.25634992 -1.36055436  2.04917837  1.63289769]
[-0.86178936 -1.27637994 -1.37009797  2.03652782  1.62997415]
[-0.85949388 -1.25812568 -1.36202884  2.05395847  1.63732118]
[-0.8626633  -1.27436926 -1.36982476  2.04423175  1.63537989]
[-0.86121534 -1.26150625 -1.36422816  2.05736249  1.64123868]
[-0.86384615 -1.27438108 -1.37047018  2.05024501  1.64017632]
[-0.86299695 -1.26532091 -1.366619    2.06035046  1.64499026]
[-0.86518758 -1.27543916 -1.37159016  2.05537249  1.6446499 ]
[-0.8647

In [146]:
nest_loss_hist

[1.3775457116279202,
 0.5949534752271084,
 0.5660533295430212,
 0.32661509448431814,
 0.35349703450208475,
 0.28506560775574064,
 0.30096658984993385,
 0.2807753773393756,
 0.2868076063823521,
 0.28055791561747806,
 0.28234211928036296,
 0.2802499673336149,
 0.28056118886670856,
 0.2797417083631791,
 0.27961406874731226,
 0.2791941938731835,
 0.2789614946083329,
 0.2786717021631436,
 0.2784275387732197,
 0.27818294527502696,
 0.27794751380662047,
 0.2777205106112599,
 0.2774946926397115,
 0.2772757304213221,
 0.27705684306902995,
 0.27684225937279683,
 0.2766279072248212,
 0.27641609655659777,
 0.2762047208494338,
 0.27599488531378175,
 0.27578557756310657,
 0.2755772850792764,
 0.2753695409383873,
 0.27516254675349666,
 0.2749560919446003,
 0.274750254586335,
 0.2745449404549746,
 0.27434017715360226,
 0.27413592220590155,
 0.2739321837148003,
 0.2737289419787573,
 0.2735261980590095,
 0.2733239422522328,
 0.2731221733224754,
 0.27292088597490893,
 0.2727200783627547,
 0.2725197471562

### Проверяем на количество ошибок

In [153]:
error_2 = 0
for idx, item in enumerate(np.around(predict(theta, X))):
    if item != Y[idx]:
        error_2 += 1
error_2

2

### Метод rmsprop

In [148]:
lr = 0.05
theta = []
theta = np.random.normal(size=(5,))
e_sq_grad = np.zeros(5)
grad = np.zeros(5)
rmsp_loss_hist = []
gamma = 0.975
eps = 0.00000001
for _ in range(1000):
    sigm = predict(theta, X)
    loss = - np.mean(np.log(sigm) * Y + np.log(1 - sigm) * (1 - Y))
    rmsp_loss_hist.append(loss)
    grad[0] = np.sum(sigm - Y)/len(sigm)
    grad[1] = np.sum((sigm - Y) * X[:, 0])/len(sigm)
    grad[2] = np.sum((sigm - Y) * X[:, 1])/len(sigm)
    grad[3] = np.sum((sigm - Y) * X[:, 2])/len(sigm)
    grad[4] = np.sum((sigm - Y) * X[:, 3])/len(sigm)
    
    e_sq_grad = gamma * e_sq_grad + (1 - gamma)  * grad ** 2
    
    theta -= lr * grad / np.sqrt(e_sq_grad + eps)
    print(theta)

[-0.13820472  0.00900214 -0.23037209 -0.34247856  1.71905736]
[-0.20545068 -0.04195224 -0.28773552 -0.37135623  1.70465983]
[-0.16544839  0.01057645 -0.24040952 -0.30364896  1.78003341]
[-0.2631539  -0.07120189 -0.32838611 -0.36253948  1.73736601]
[-0.18914963  0.01373425 -0.2479837  -0.26513655  1.84029944]
[-0.30889421 -0.09158772 -0.3588808  -0.34844823  1.77385043]
[-0.22535212  0.00216531 -0.26929667 -0.24321468  1.88413154]
[-0.33674681 -0.09651427 -0.37295862 -0.32209173  1.82060979]
[-0.27099115 -0.02050444 -0.30113003 -0.23411937  1.91423466]
[-0.35951985 -0.09743442 -0.382714   -0.29314711  1.86857985]
[-0.31458766 -0.04213269 -0.33166386 -0.2252935   1.94269777]
[-0.38360292 -0.10012586 -0.3941557  -0.26653875  1.91342094]
[-0.35422861 -0.06028978 -0.35862703 -0.213693    1.97299264]
[-0.40990142 -0.10521536 -0.40798295 -0.24250388  1.95528205]
[-0.39094221 -0.07571389 -0.38283319 -0.19964845  2.00518607]
[-0.43804762 -0.1121962  -0.42372046 -0.22034538  1.99506295]
[-0.4257

In [149]:
rmsp_loss_hist

[2.468431075710186,
 0.5662986385220337,
 0.5697761800380254,
 0.5806938999887963,
 0.5928854826656506,
 0.6114076902774189,
 0.6060927722100671,
 0.6046136317370772,
 0.5788098057998624,
 0.5669426314966645,
 0.5474964519751943,
 0.5375831331551968,
 0.5260431835985918,
 0.519018866146463,
 0.5116863224765706,
 0.5064258849111968,
 0.5010930279580532,
 0.4967794107672072,
 0.4924215761523643,
 0.4886285370322948,
 0.4847892052125269,
 0.48131651202453507,
 0.4777952309601015,
 0.474562260447032,
 0.4712810610811221,
 0.4682788480075007,
 0.4652301406381732,
 0.4625085861522955,
 0.45973992256941826,
 0.4574162890141247,
 0.4550287376130235,
 0.4533033368819538,
 0.4514324066135002,
 0.4505696690752887,
 0.4492766442247587,
 0.4494445898280725,
 0.4484255115607382,
 0.4493024453040649,
 0.44759653907647207,
 0.44811363757997896,
 0.4445913499090857,
 0.44363406041050907,
 0.43825564034549175,
 0.43573495722225325,
 0.4296378887383827,
 0.42630400443317734,
 0.42058494674216845,
 0.4171

### Проверка на количество ошибок

In [154]:
error_3 = 0
for idx, item in enumerate(np.around(predict(theta, X))):
    if item != Y[idx]:
        error_3 += 1
error_3

2