<a href="https://colab.research.google.com/github/po1sonrom/netology_feature_engineering/blob/master/second.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Строим логистическую регрессию - угадываем пол спортсмена по признакам

https://www.kaggle.com/rio2016/olympic-games

In [3]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv( 'athletes.csv' )
data.head()

id            name nationality  ... gold silver  bronze
0  736041664  A Jesus Garcia         ESP  ...    0      0       0
1  532037425      A Lam Shin         KOR  ...    0      0       0
2  435962603     Aaron Brown         CAN  ...    0      0       1
3  521041435      Aaron Cook         MDA  ...    0      0       0
4   33922579      Aaron Gate         NZL  ...    0      0       0

[5 rows x 11 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11538 entries, 0 to 11537
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           11538 non-null  int64  
 1   name         11538 non-null  object 
 2   nationality  11538 non-null  object 
 3   sex          11538 non-null  object 
 4   dob          11537 non-null  object 
 5   height       11208 non-null  float64
 6   weight       10879 non-null  float64
 7   sport        11538 non-null  object 
 8   gold         11538 non-null  int64  
 9   silver       11538 non-null  int64  
 10  bronze       11538 non-null  int64  
dtypes: float64(2), int64(4), object(5)
memory usage: 991.7+ KB


#### Попробуем угадать пол на основе роста, веса и вида спорта

Посмотрим много ли в наших признаках пустых значений

In [8]:
data[ pd.isnull( data['height'] ) ].head()

id                name nationality  ... gold silver  bronze
12  258556239          Abbas Qali         IOA  ...    0      0       0
47  469953606  Abdoullah Bamoussa         ITA  ...    0      0       0
50  325809293          Abdul Omar         GHA  ...    0      0       0
52  262868423  Abdulaziz Alshatti         IOA  ...    0      0       0
56  897549624   Abdullah Hel Baki         BAN  ...    0      0       0

[5 rows x 11 columns]

In [9]:
print('Для height пустых строк {}'.format( len( data[ pd.isnull( data['height'] ) ] ) ))
print('Для weight пустых строк {}'.format( len( data[ pd.isnull( data['weight'] ) ] ) ))
print('Для sport пустых строк {}'.format( len( data[ pd.isnull( data['sport'] ) ] ) ))
print('Всего строк в наборе {}'.format( len( data ) ))

Для height пустых строк 330
Для weight пустых строк 659
Для sport пустых строк 0
Всего строк в наборе 11538


In [10]:
data['height'].unique()

array([1.72, 1.68, 1.98, 1.83, 1.81, 1.8 , 2.05, 1.93, 1.65, 1.7 , 1.75,
        nan, 1.61, 1.78, 1.76, 2.1 , 1.73, 1.85, 1.77, 1.9 , 1.86, 1.74,
       1.6 , 2.07, 1.88, 1.66, 1.62, 1.87, 2.03, 1.69, 1.82, 1.89, 1.94,
       1.95, 1.71, 1.84, 1.91, 1.67, 2.02, 1.58, 1.63, 1.79, 1.97, 1.56,
       1.55, 1.57, 1.46, 1.92, 1.64, 1.53, 1.99, 1.96, 2.  , 2.04, 1.47,
       1.52, 2.01, 1.51, 1.59, 2.08, 1.37, 1.5 , 1.45, 2.06, 1.54, 2.11,
       1.43, 1.49, 1.33, 1.48, 1.44, 2.13, 2.09, 2.21, 2.18, 1.21, 1.38,
       1.34, 2.15, 2.17, 1.42, 1.4 , 2.14])

In [11]:
# обнуляем ячейки с отсутствием данных
data = data[ pd.isnull( data['height'] ) == 0 ]
data = data[ pd.isnull( data['weight'] ) == 0 ]

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10858 entries, 0 to 11537
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           10858 non-null  int64  
 1   name         10858 non-null  object 
 2   nationality  10858 non-null  object 
 3   sex          10858 non-null  object 
 4   dob          10858 non-null  object 
 5   height       10858 non-null  float64
 6   weight       10858 non-null  float64
 7   sport        10858 non-null  object 
 8   gold         10858 non-null  int64  
 9   silver       10858 non-null  int64  
 10  bronze       10858 non-null  int64  
dtypes: float64(2), int64(4), object(5)
memory usage: 1017.9+ KB


In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
# попробуем выбрать какие-нибудь признаки
selectedColumns = data[ [ 'height', 'sport', 'sex' ] ]

# столбец sport является категориальной переменной
# переведем ее в значения 0 и 1, добавив столбцы с соответствующими названиями
X = pd.get_dummies( selectedColumns, columns = [ 'sport' ] )

# столбец sex является целевой переменной, удаляем его из X
del X['sex']
X.head()

height  sport_aquatics  ...  sport_weightlifting  sport_wrestling
0    1.72               0  ...                    0                0
1    1.68               0  ...                    0                0
2    1.98               0  ...                    0                0
3    1.83               0  ...                    0                0
4    1.81               0  ...                    0                0

[5 rows x 28 columns]

In [15]:
# целевая переменная (столбец sex) снова является категориальной
# переведем значения столбца в числа, оставив один столбец

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [33]:
le.fit( data['sex'] ) #labelEncoding переводит строки в численные значения

LabelEncoder()

In [17]:
le.classes_

array(['female', 'male'], dtype=object)

In [18]:
# пример "расшировки" столбца sex

le.transform( [ 'male', 'female', 'male' ] )

array([1, 0, 1])

In [19]:
# записываем в переменную y преобразованный столбец sex

y = pd.Series( data = le.transform( data['sex'] ) )
y.head()

0    1
1    0
2    1
3    1
4    1
dtype: int64

In [20]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 


model = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000))


In [21]:
#model = LogisticRegression()

In [22]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
#на train обучаем модель, а на test проверяем модель

In [23]:
# обучаем модель

model.fit( X_train, y_train )
predictions = model.predict_proba( X_test ) #возвращает вроятности классов

In [24]:
predictions[:5]

array([[0.38105108, 0.61894892],
       [0.12674716, 0.87325284],
       [0.7348151 , 0.2651849 ],
       [0.03887425, 0.96112575],
       [0.12952041, 0.87047959]])

In [25]:
# сравниваем факт с предсказаниями


zip( predictions[:, 1], y )

In [26]:
model.predict(X_test)

array([1, 1, 0, ..., 0, 0, 0])

In [27]:
model.score(X_train, y_train)

0.7988157894736843

In [28]:
model.score(X_test, y_test)

0.7955801104972375

In [29]:
from sklearn.svm import SVC


clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) #gamma='auto' можно не задавать, так как в данном случае параметр стандартного значения
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='auto', kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [30]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='auto', kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [34]:
clf.predict(X_test) #наше предсказание

array([1, 1, 0, ..., 0, 0, 0])

In [35]:
clf.score(X_train, y_train)

0.7992105263157895

In [37]:
clf.score(X_test, y_test)

0.7965009208103131